volumes:
    mysql-data:

services:
    mysql:
        image: docker.io/library/mysql:${VERSION:-latest}
        ports:
            - "${PORT:-3306}:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - mysql-data:/var/lib/mysql
